local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<C-F10>", function () mark.add_file() end)
vim.keymap.set("n", "<C-F9>", function () mark.rm_file() end)

vim.keymap.set("n", "<C-F12>", function () ui.toggle_quick_menu() end)

vim.keymap.set("n", "<F1>", function () ui.nav_file(1) end)
vim.keymap.set("n", "<F2>", function () ui.nav_file(2) end)
vim.keymap.set("n", "<F3>", function () ui.nav_file(3) end)
--vim.keymap.set("n", "<F4>", function () ui.nav_file(4) end)
vim.keymap.set("n", "<F5>", function () ui.nav_file(5) end)
vim.keymap.set("n", "<F6>", function () ui.nav_file(6) end)
vim.keymap.set("n", "<F7>", function () ui.nav_file(7) end)
vim.keymap.set("n", "<F8>", function () ui.nav_file(8) end)
vim.keymap.set("n", "<F9>", function () ui.nav_file(9) end)
vim.keymap.set("n", "<F10>", function () ui.nav_file(10) end)
vim.keymap.set("n", "<F11>", function () ui.nav_file(11) end)
vim.keymap.set("n", "<F12>", function () ui.nav_file(12) end)

vim.keymap.set("n", "<A-F1>", function () mark.set_current_at(1) end)
vim.keymap.set("n", "<A-F2>", function () mark.set_current_at(2) end)
vim.keymap.set("n", "<A-F3>", function () mark.set_current_at(3) end)
--vim.keymap.set("n", "<A-F4>", function () mark.set_current_at(4) end)
vim.keymap.set("n", "<A-F5>", function () mark.set_current_at(5) end)
vim.keymap.set("n", "<A-F6>", function () mark.set_current_at(6) end)
vim.keymap.set("n", "<A-F7>", function () mark.set_current_at(7) end)
vim.keymap.set("n", "<A-F8>", function () mark.set_current_at(8) end)
vim.keymap.set("n", "<A-F9>", function () mark.set_current_at(9) end)
vim.keymap.set("n", "<A-F10>", function () mark.set_current_at(10) end)
vim.keymap.set("n", "<A-F11>", function () mark.set_current_at(11) end)
vim.keymap.set("n", "<A-F12>", function () mark.set_current_at(12) end)
